apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-python-deployment
  labels:
    app: app-python
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-python
  template:
    metadata:
      labels:
        app: app-python
    spec:
      containers:
        - name: app-python
          image: yuribrigido/app-python:90290433edd96a663c0ccc9ff155534cc3b8aee6
          ports:
            - containerPort: 8080
