apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-python-deployment
  labels:
    app: app-python
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-python
  template:
    metadata:
      labels:
        app: app-python
    spec:
      containers:
        - name: app-python
          image: yuribrigido/app-python:79c4d07f0581eea3927e8d4ea8f812805d391cef
          ports:
            - containerPort: 8080
